security:
    encoders:
        App\Entity\Client:
            algorithm: 'argon2i'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: username

    firewalls:
        dev:
            pattern: ^/ #_(profiler|wdt)
            security: false
        api:
            pattern:   ^/api/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        login:
            pattern:  ^/token
            stateless: true
            anonymous: true
            json_login:
                check_path: /token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure